# START_FEATURE elastic_beanstalk
# https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html
ElasticBeanstalk:
  # aws elasticbeanstalk list-available-solution-stacks --region us-east-1
  SolutionStackName: "64bit Amazon Linux 2 * Python 3.8"
  NumProcesses: "1"
  InstanceTypes: "t3.micro"
  IamInstanceProfile: "aws-elasticbeanstalk-ec2-role"
  AssociatePublicIpAddress: True
  ProxyServer: "apache"  # apache, nginx
  InstancePublicSubnets: True
  # Omit the load balancer block to have it be not load balanced
  LoadBalancer:
    LoadBalancerType: "application"
    SSLCertificateId: null
    ELBScheme: "public"  # public, private
    MinSize: "1"
    MaxSize: "1"
    PublicSubnets: True
  # Omit the managed updates block to disable managed updates
  ManagedUpdates:
    PreferredStartTime: "TUE:05:15"
    UpdateLevel: "minor"  # patch, minor
    ServiceRoleForManagedUpdates: "AWSServiceRoleForElasticBeanstalkManagedUpdates"
RDS:
  AllocatedStorage: 100
  DBInstanceClass: "db.t3.micro"
  MasterUsername: "db_admin"
  BackupRetentionPeriod: 30
  MultiAZ: False
  AutoMinorVersionUpgrade: False
  PubliclyAccessible: False
  StorageType: "gp2"
  StorageEncrypted: True
  CopyTagsToSnapshot: True
  MonitoringInterval: 0  # 60 but 0 disables this
  DeletionProtection: False
  MaxAllocatedStorage: 1000
  Postgres:
    DBName: "ebdb"
    Engine: "postgres"
    EngineVersion: "15.*"
    Port: 5432
    DBParameterGroupName: "default.postgres15"
    LicenseModel: "postgresql-license"
# END_FEATURE elastic_beanstalk
